### PR TITLE
Merging Workflows

### PR DESCRIPTION
**Pull request by rahul799**

### CODE REVIEW

**Comment by oliveralka** [comment]
@rahul799 is that ready to merge?

**Comment by timosachsenberg** [comment]
If possible also document in the README.MD of pyopenms-extra that there exists this action and briefly say what the action is doing

**Comment by rahul799** [comment]
Yes @oliveralka . You can merge it. Once the latest pyopenMS-package is pushed to the `master+ipynb` branch, I will raise another PR to add a post-build script. But you can merge it for now.

> If possible also document in the README.MD of pyopenms-extra that there exists this action and briefly say what the action is doing
Yes sure. Will do.

**Comment by oliveralka** [comment]
> Yes @oliveralka . You can merge it. Once the latest pyopenMS-package is pushed to the `master+ipynb` branch, I will raise another PR to add a post-build script. But you can merge it for now.
> 
> > If possible also document in the README.MD of pyopenms-extra that there exists this action and briefly say what the action is doing
> 
> Yes sure. Will do.

Please add the README.MD to the next PR.

**Pull request merged**
