### PR TITLE
Ropenms

### PR DESCRIPTION
**Pull request by hroest**

### CODE REVIEW

**Comment by hroest** [comment]
@Leon-Bichmann any comments? I would suggest to add the page into the index just before the developer info

**Comment by Leon-Bichmann** [comment]
Hey, it looks good to me!

Just one more thing:
I took out the example with:

exp$getNrChromatograms()
0

Any idea why the BSA1.mzML has no chromatograms?

**Comment by hroest** [comment]
> Any idea why the BSA1.mzML has no chromatograms?

probably because its a pure LC-MS/MS run without any chromatogram measurements in there (no PRM/SRM/DIA). Most MS runs are like this (except if you compute a TIC explicitly)

**Comment by Leon-Bichmann** [comment]
ok I see, the definition of a chromatogram was not as clear to me yet. I thought every MS measurement is a stack of chromatograms in principle.

**Comment by hroest** [comment]
>  I thought every MS measurement is a stack of chromatograms in principle.

no, its the other way around. Every MS measurement is a series of spectra (e.g. that is what the instrument measures, one spectrum after the other).

**Pull request merged**
