### PR TITLE
Integrating Binder

### PR DESCRIPTION
**Pull request by rahul799**
In this PR I have added a CI/CD pipeline that will build the ipynb notebooks and push it to 'master+ipynb' branch.

### CODE REVIEW

**Comment by rahul799** [comment]
@timosachsenberg @okohlbacher  This PR is ready for merge.

**Comment by timosachsenberg** [comment]
What happens in the case of our nightly / latest pyopenms documentation.
E.g., if the documentation has new features that are not yet supported by the official pyopenms on pip?
I guess the ipynb generation still works but execution fails?

**Comment by rahul799** [comment]
Sorry, I didn't get your question maybe because I have less context about the release pipeline. So whenever there is a change in the .rst files and if the PR is raised, so ipynb notebooks will be generated each time. But I think we must run the pipeline only after the PR is merged, otherwise, our 'master+ipynb' branch will contain the changes which are yet to be merged.

**Comment by timosachsenberg** [comment]
We sometimes add new features to pyopenms and update the documentation accordingly.
This means that executing the generated ipynb that use the new feature will fail because the pyopenms they use is an official release (e.g., 2.6.0) and doesn't contain it yet.
@jpfeuffer we have our pyopenms build artefacts in openms/openms. Is there an easy way to reference those if we build readethedocs latest?

**Comment by jpfeuffer** [comment]
Unfortunately, GitHub does still not provide an official action to copy artifacts from other repos. IIRC there are third-party actions to do that though. We might need to set up GitHub Tokens or secrets for that though.

**Comment by timosachsenberg** [comment]
This is linked from the official github documentation https://github.com/actions/download-artifact . Does this work?

**Comment by jpfeuffer** [comment]
Nope not over repositories.

**Comment by jpfeuffer** [comment]
https://github.com/actions/download-artifact/issues/83
I signed up for that issue years ago.

**Comment by rahul799** [comment]
I have used this template earlier. This helps to use the artifact in
between two different jobs in a same workflow. Not between repositories.

**Comment by jpfeuffer** [comment]
You can use https://github.com/dawidd6/action-download-artifact
I used it successfully before. But as I said, you might need to setup credentials.

**Comment by rahul799** [comment]
Hi @jpfeuffer, I have made[ the workflow](https://github.com/rahul799/pyopenms-extra/blob/master+ipynb/.github/workflows/download-pyopenms.yml) using  https://github.com/dawidd6/action-download-artifact, and I am trying to download the artifacts generated during [this](https://github.com/OpenMS/OpenMS/runs/2663443227?check_suite_focus=true) build, but every time I get the [not found error](https://github.com/rahul799/pyopenms-extra/runs/2826657361?check_suite_focus=true#step:3:14). I saw that artifacts are available for 90 days in the GitHub documentation, but I can't find any in the dashboard here https://github.com/OpenMS/OpenMS/actions/runs/874237068 . Am I doing something wrong in the workflow, or do we have a bug?

**Comment by jpfeuffer** [comment]
Hi, Not sure but maybe you need to search for the pyopenms-wheels from the nightly branch builds. These are the real daily builds.

**Comment by jpfeuffer** [comment]
I don't know if you can specify a branch. And I don't know if you can check for the last successful build. But that would maybe solve it.

I am not sure if this connection via GitHub artifacts is the right way to go, @timosachsenberg 
Seems very unstable.

**Comment by rahul799** [comment]
@jpfeuffer Thank you for the help :smiley: . As we have some limitations with the download-artifact actions, we decided to build the new pyopenms-package in this repository itself and use it. That seemed to be the best possible option for now.

**Pull request merged**
